# Generated by Django 5.2.6 on 2025-09-14 04:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latest_update', models.CharField(max_length=255)),
                ('Update_text', models.TextField()),
                ('delivered_or_complain', models.TextField()),
                ('Arrived_location', models.TextField()),
                ('Arrived_location_date', models.TextField()),
                ('Add_date_to_next_facility', models.TextField()),
                ('package_arrived_at_Shiparama_Facility', models.TextField()),
                ('package_arrived_at_Shiparama_Facility_date', models.TextField()),
                ('created', models.DateField(auto_now_add=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.track')),
            ],
        ),
    ]
