# Generated by Django 5.2.6 on 2025-09-14 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingpackage',
            name='Add_date_to_next_facility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='Arrived_location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='Arrived_location_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='Update_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='delivered_or_complain',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='latest_update',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='package_arrived_at_Shiparama_Facility',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='package_arrived_at_Shiparama_Facility_date',
            field=models.TextField(blank=True, null=True),
        ),
    ]
