# Generated by Django 5.2.6 on 2025-09-14 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trackingpackage_add_date_to_next_facility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackingpackage',
            name='Add_date_to_next_facility',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='Arrived_location',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='Arrived_location_date',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trackingpackage',
            name='package_arrived_at_Shiparama_Facility_date',
            field=models.CharField(blank=True, null=True),
        ),
    ]
