# Generated by Django 5.2.6 on 2025-09-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_label'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='track',
            new_name='tracking_id',
        ),
        migrations.RenameField(
            model_name='trackingpackage',
            old_name='track',
            new_name='tracking_id',
        ),
    ]
