# Generated by Django 5.2.6 on 2025-09-14 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_track_label_tracking_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='label',
            old_name='tracking_id',
            new_name='track',
        ),
        migrations.RenameField(
            model_name='trackingpackage',
            old_name='tracking_id',
            new_name='track',
        ),
    ]
