# Generated by Django 5.2.6 on 2025-09-14 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_complaint_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
